#ifndef __WORD_POOL_H__
#define __WORD_POOL_H__
typedef struct word_pool_{
    char string[20];
}word_t;

#define WORD_LIST \
    WORD_LIST_FILL("COMPUTER"),\
    WORD_LIST_FILL("COOL"),\
    WORD_LIST_FILL("BATMAN"),\
    WORD_LIST_FILL("SCIENCE"),\
    WORD_LIST_FILL("STATION"),\
    WORD_LIST_FILL("SUBMISSION"),\
    WORD_LIST_FILL("FRICTIONAL"),\
    WORD_LIST_FILL("TUBELIGHT"),\
    WORD_LIST_FILL("TRANSMISSION"),\
    WORD_LIST_FILL("COORDINATION"),\
    WORD_LIST_FILL("explain"),\
    WORD_LIST_FILL("amuck"),\
    WORD_LIST_FILL("smash"),\
    WORD_LIST_FILL("impress"),\
    WORD_LIST_FILL("rapid"),\
    WORD_LIST_FILL("impolite"),\
    WORD_LIST_FILL("coordinated"),\
    WORD_LIST_FILL("silky"),\
    WORD_LIST_FILL("grass"),\
    WORD_LIST_FILL("wait"),\
    WORD_LIST_FILL("naive"),\
    WORD_LIST_FILL("accidental"),\
    WORD_LIST_FILL("ask"),\
    WORD_LIST_FILL("hesitant"),\
    WORD_LIST_FILL("copper"),\
    WORD_LIST_FILL("fork"),\
    WORD_LIST_FILL("burly"),\
    WORD_LIST_FILL("gifted"),\
    WORD_LIST_FILL("flippant"),\
    WORD_LIST_FILL("neck"),\
    WORD_LIST_FILL("rural"),\
    WORD_LIST_FILL("married"),\
    WORD_LIST_FILL("delicate"),\
    WORD_LIST_FILL("edge"),\
    WORD_LIST_FILL("crawl"),\
    WORD_LIST_FILL("onerous"),\
    WORD_LIST_FILL("command"),\
    WORD_LIST_FILL("maniacal"),\
    WORD_LIST_FILL("frantic"),\
    WORD_LIST_FILL("note"),\
    WORD_LIST_FILL("branch"),\
    WORD_LIST_FILL("cherries"),\
    WORD_LIST_FILL("smiling"),\
    WORD_LIST_FILL("shop"),\
    WORD_LIST_FILL("unbiased"),\
    WORD_LIST_FILL("moan"),\
    WORD_LIST_FILL("bolt"),\
    WORD_LIST_FILL("shiny"),\
    WORD_LIST_FILL("dog"),\
    WORD_LIST_FILL("face"),\
    WORD_LIST_FILL("smoggy"),\
    WORD_LIST_FILL("damaging"),\
    WORD_LIST_FILL("overrated"),\
    WORD_LIST_FILL("stereotyped"),\
    WORD_LIST_FILL("enter"),\
    WORD_LIST_FILL("condition"),\
    WORD_LIST_FILL("yarn"),\
    WORD_LIST_FILL("kindly"),\
    WORD_LIST_FILL("heavenly"),\
    WORD_LIST_FILL("wrap"),\
    WORD_LIST_FILL("ruddy"),\
    WORD_LIST_FILL("dashing"),\
    WORD_LIST_FILL("mundane"),\
    WORD_LIST_FILL("billowy"),\
    WORD_LIST_FILL("bare"),\
    WORD_LIST_FILL("waiting"),\
    WORD_LIST_FILL("false"),\
    WORD_LIST_FILL("trains"),\
    WORD_LIST_FILL("pop"),\
    WORD_LIST_FILL("painstaking"),\
    WORD_LIST_FILL("receptive"),\
    WORD_LIST_FILL("shiver"),\
    WORD_LIST_FILL("courageous"),\
    WORD_LIST_FILL("air"),\
    WORD_LIST_FILL("signal"),\
    WORD_LIST_FILL("amusing"),\
    WORD_LIST_FILL("metal"),\
    WORD_LIST_FILL("live"),\
    WORD_LIST_FILL("sleep"),\
    WORD_LIST_FILL("subdued"),\
    WORD_LIST_FILL("well-groomed"),\
    WORD_LIST_FILL("devilish"),\
    WORD_LIST_FILL("telephone"),\
    WORD_LIST_FILL("mindless"),\
    WORD_LIST_FILL("physical"),\
    WORD_LIST_FILL("knowing"),\
    WORD_LIST_FILL("grubby"),\
    WORD_LIST_FILL("abundant"),\
    WORD_LIST_FILL("selective"),\
    WORD_LIST_FILL("accept"),\
    WORD_LIST_FILL("dress"),\
    WORD_LIST_FILL("ill"),\
    WORD_LIST_FILL("title"),\
    WORD_LIST_FILL("film"),\
    WORD_LIST_FILL("mark"),\
    WORD_LIST_FILL("board"),\
    WORD_LIST_FILL("degree"),\
    WORD_LIST_FILL("health"),\
    WORD_LIST_FILL("blush"),\
    WORD_LIST_FILL("basketball"),\
    WORD_LIST_FILL("hot"),\
    WORD_LIST_FILL("phobic"),\
    WORD_LIST_FILL("unsightly"),\
    WORD_LIST_FILL("rinse"),\
    WORD_LIST_FILL("soothe"),\
    WORD_LIST_FILL("pinch"),\
    WORD_LIST_FILL("treat"),\
    WORD_LIST_FILL("mint"),\
    WORD_LIST_FILL("paddle"),\
    WORD_LIST_FILL("finger"),\
    WORD_LIST_FILL("verse"),\
    WORD_LIST_FILL("thrill"),\
    WORD_LIST_FILL("ceaseless"),\
    WORD_LIST_FILL("part"),\
    WORD_LIST_FILL("airport"),\
    WORD_LIST_FILL("thoughtless"),\
    WORD_LIST_FILL("boil"),\
    WORD_LIST_FILL("cart"),\
    WORD_LIST_FILL("knock"),\
    WORD_LIST_FILL("wealth"),\
    WORD_LIST_FILL("stare"),\
    WORD_LIST_FILL("dark"),\
    WORD_LIST_FILL("sky"),\
    WORD_LIST_FILL("meaty"),\
    WORD_LIST_FILL("public"),\
    WORD_LIST_FILL("hurt"),\
    WORD_LIST_FILL("road"),\
    WORD_LIST_FILL("building"),\
    WORD_LIST_FILL("wandering"),\
    WORD_LIST_FILL("lie"),\
    WORD_LIST_FILL("resonant"),\
    WORD_LIST_FILL("early"),\
    WORD_LIST_FILL("office"),\
    WORD_LIST_FILL("poised"),\
    WORD_LIST_FILL("place"),\
    WORD_LIST_FILL("question"),\
    WORD_LIST_FILL("temporary"),\
    WORD_LIST_FILL("rampant"),\
    WORD_LIST_FILL("mouth"),\
    WORD_LIST_FILL("unadvised"),\
    WORD_LIST_FILL("quaint"),\
    WORD_LIST_FILL("abnormal"),\
    WORD_LIST_FILL("avoid"),\
    WORD_LIST_FILL("delicious"),\
    WORD_LIST_FILL("sisters"),\
    WORD_LIST_FILL("sneaky"),\
    WORD_LIST_FILL("plucky"),\
    WORD_LIST_FILL("hysterical"),\
    WORD_LIST_FILL("bells"),\
    WORD_LIST_FILL("adjustment"),\
    WORD_LIST_FILL("coat"),\
    WORD_LIST_FILL("sudden"),\
    WORD_LIST_FILL("glass"),\
    WORD_LIST_FILL("chess"),\
    WORD_LIST_FILL("supply"),\
    WORD_LIST_FILL("consider"),\
    WORD_LIST_FILL("sharp"),\
    WORD_LIST_FILL("fail"),\
    WORD_LIST_FILL("arithmetic"),\
    WORD_LIST_FILL("spiky"),\
    WORD_LIST_FILL("soup"),\
    WORD_LIST_FILL("count"),\
    WORD_LIST_FILL("apathetic"),\
    WORD_LIST_FILL("obnoxious"),\
    WORD_LIST_FILL("gorgeous"),\
    WORD_LIST_FILL("puffy"),\
    WORD_LIST_FILL("highfalutin"),\
    WORD_LIST_FILL("jittery"),\
    WORD_LIST_FILL("bite"),\
    WORD_LIST_FILL("dinosaurs"),\
    WORD_LIST_FILL("aloof"),\
    WORD_LIST_FILL("melt"),\
    WORD_LIST_FILL("relation"),\
    WORD_LIST_FILL("desire"),\
    WORD_LIST_FILL("lettuce"),\
    WORD_LIST_FILL("bubble"),\
    WORD_LIST_FILL("feigned"),\
    WORD_LIST_FILL("thick"),\
    WORD_LIST_FILL("laborer"),\
    WORD_LIST_FILL("far"),\
    WORD_LIST_FILL("stone"),\
    WORD_LIST_FILL("cabbage"),\
    WORD_LIST_FILL("moldy"),\
    WORD_LIST_FILL("murder"),\
    WORD_LIST_FILL("odd"),\
    WORD_LIST_FILL("rescue"),\
    WORD_LIST_FILL("pet"),\
    WORD_LIST_FILL("optimal"),\
    WORD_LIST_FILL("pour"),\
    WORD_LIST_FILL("error"),\
    WORD_LIST_FILL("languid"),\
    WORD_LIST_FILL("sable"),\
    WORD_LIST_FILL("filthy"),\
    WORD_LIST_FILL("blind"),\
    WORD_LIST_FILL("legal"),\
    WORD_LIST_FILL("gate"),\
    WORD_LIST_FILL("earn"),\
    WORD_LIST_FILL("wing"),\
    WORD_LIST_FILL("jazzy"),\
    WORD_LIST_FILL("launch"),\
    WORD_LIST_FILL("rice"),\
    WORD_LIST_FILL("ragged"),\
    WORD_LIST_FILL("turkey"),\
    WORD_LIST_FILL("fantastic"),\
    WORD_LIST_FILL("careful"),\
    WORD_LIST_FILL("flowers"),\
    WORD_LIST_FILL("nondescript"),\
    WORD_LIST_FILL("brush"),\
    WORD_LIST_FILL("itch"),\
    WORD_LIST_FILL("frogs"),\
    WORD_LIST_FILL("telling"),\
    WORD_LIST_FILL("yard"),\
    WORD_LIST_FILL("needy"),\
    WORD_LIST_FILL("raspy"),\
    WORD_LIST_FILL("tank"),\
    WORD_LIST_FILL("work"),\
    WORD_LIST_FILL("joyous"),\
    WORD_LIST_FILL("purpose"),\
    WORD_LIST_FILL("wretched"),\
    WORD_LIST_FILL("eggs"),\
    WORD_LIST_FILL("trick"),\
    WORD_LIST_FILL("bizarre"),\
    WORD_LIST_FILL("pest"),\
    WORD_LIST_FILL("post"),\
    WORD_LIST_FILL("secret"),\
    WORD_LIST_FILL("tan"),\
    WORD_LIST_FILL("oafish"),\
    WORD_LIST_FILL("form"),\
    WORD_LIST_FILL("sparkling"),\
    WORD_LIST_FILL("befitting"),\
    WORD_LIST_FILL("rifle"),\
    WORD_LIST_FILL("instinctive"),\
    WORD_LIST_FILL("last"),\
    WORD_LIST_FILL("lonely"),\
    WORD_LIST_FILL("needless"),\
    WORD_LIST_FILL("flimsy"),\
    WORD_LIST_FILL("escape"),\
    WORD_LIST_FILL("salt"),\
    WORD_LIST_FILL("knot"),\
    WORD_LIST_FILL("parched"),\
    WORD_LIST_FILL("ossified"),\
    WORD_LIST_FILL("quarter"),\
    WORD_LIST_FILL("sheet"),\
    WORD_LIST_FILL("boy"),\
    WORD_LIST_FILL("resolute"),\
    WORD_LIST_FILL("yellow"),\
    WORD_LIST_FILL("precede"),\
    WORD_LIST_FILL("experience"),\
    WORD_LIST_FILL("cheap"),\
    WORD_LIST_FILL("enormous"),\
    WORD_LIST_FILL("aunt"),\
    WORD_LIST_FILL("calculator"),\
    WORD_LIST_FILL("endurable"),\
    WORD_LIST_FILL("spurious"),\
    WORD_LIST_FILL("crow"),\
    WORD_LIST_FILL("dear"),\
    WORD_LIST_FILL("exultant"),\
    WORD_LIST_FILL("regular"),\
    WORD_LIST_FILL("wonder"),\
    WORD_LIST_FILL("glue"),\
    WORD_LIST_FILL("brawny"),\
    WORD_LIST_FILL("abounding"),\
    WORD_LIST_FILL("waves"),\
    WORD_LIST_FILL("unaccountable"),\
    WORD_LIST_FILL("cool"),\
    WORD_LIST_FILL("start"),\
    WORD_LIST_FILL("example"),\
    WORD_LIST_FILL("digestion"),\
    WORD_LIST_FILL("steep"),\
    WORD_LIST_FILL("receive"),\
    WORD_LIST_FILL("coast"),\
    WORD_LIST_FILL("enchanted"),\
    WORD_LIST_FILL("warlike"),\
    WORD_LIST_FILL("decorate"),\
    WORD_LIST_FILL("helpless"),\
    WORD_LIST_FILL("innate"),\
    WORD_LIST_FILL("dam"),\
    WORD_LIST_FILL("babies"),\
    WORD_LIST_FILL("free"),\
    WORD_LIST_FILL("remain"),\
    WORD_LIST_FILL("gruesome"),\
    WORD_LIST_FILL("blue"),\
    WORD_LIST_FILL("corn"),\
    WORD_LIST_FILL("earthquake"),\
    WORD_LIST_FILL("cream"),\
    WORD_LIST_FILL("perfect"),\
    WORD_LIST_FILL("position"),\
    WORD_LIST_FILL("jail"),\
    WORD_LIST_FILL("polite"),\
    WORD_LIST_FILL("puny"),\
    WORD_LIST_FILL("acidic"),\
    WORD_LIST_FILL("badge"),\
    WORD_LIST_FILL("normal"),\
    WORD_LIST_FILL("army"),\
    WORD_LIST_FILL("analyze"),\
    WORD_LIST_FILL("statuesque"),\
    WORD_LIST_FILL("bat"),\
    WORD_LIST_FILL("amount"),\
    WORD_LIST_FILL("entertain"),\
    WORD_LIST_FILL("scary"),\
    WORD_LIST_FILL("grain"),\
    WORD_LIST_FILL("sleet"),\
    WORD_LIST_FILL("ratty"),\
    WORD_LIST_FILL("irate"),\
    WORD_LIST_FILL("idiotic"),\
    WORD_LIST_FILL("gather"),\
    WORD_LIST_FILL("team"),\
    WORD_LIST_FILL("thaw"),\
    WORD_LIST_FILL("jobless"),\
    WORD_LIST_FILL("swanky"),\
    WORD_LIST_FILL("drunk"),\
    WORD_LIST_FILL("crown"),\
    WORD_LIST_FILL("tongue"),\
    WORD_LIST_FILL("terrify"),\
    WORD_LIST_FILL("door"),\
    WORD_LIST_FILL("need"),\
    WORD_LIST_FILL("station"),\
    WORD_LIST_FILL("books"),\
    WORD_LIST_FILL("train"),\
    WORD_LIST_FILL("motionless"),\
    WORD_LIST_FILL("reign"),\
    WORD_LIST_FILL("youthful"),\
    WORD_LIST_FILL("plot"),\
    WORD_LIST_FILL("retire"),\
    WORD_LIST_FILL("decisive"),\
    WORD_LIST_FILL("infamous"),\
    WORD_LIST_FILL("tempt"),\
    WORD_LIST_FILL("straight"),\
    WORD_LIST_FILL("floor"),\
    WORD_LIST_FILL("fretful"),\
    WORD_LIST_FILL("decide"),\
    WORD_LIST_FILL("flavor"),\
    WORD_LIST_FILL("earth"),\
    WORD_LIST_FILL("children"),\
    WORD_LIST_FILL("jumbled"),\
    WORD_LIST_FILL("hope"),\
    WORD_LIST_FILL("unnatural"),\
    WORD_LIST_FILL("drop"),\
    WORD_LIST_FILL("calm"),\
    WORD_LIST_FILL("base"),\
    WORD_LIST_FILL("somber"),\
    WORD_LIST_FILL("identify"),\
    WORD_LIST_FILL("hanging"),\
    WORD_LIST_FILL("vast"),\
    WORD_LIST_FILL("unique"),\
    WORD_LIST_FILL("room"),\
    WORD_LIST_FILL("jelly"),\
    WORD_LIST_FILL("reduce"),\
    WORD_LIST_FILL("shrug"),\
    WORD_LIST_FILL("grin"),\
    WORD_LIST_FILL("wary"),\
    WORD_LIST_FILL("crash"),\
    WORD_LIST_FILL("descriptive"),\
    WORD_LIST_FILL("birds"),\
    WORD_LIST_FILL("baseball"),\
    WORD_LIST_FILL("truck"),\
    WORD_LIST_FILL("mellow"),\
    WORD_LIST_FILL("act"),\
    WORD_LIST_FILL("annoying"),\
    WORD_LIST_FILL("flat"),\
    WORD_LIST_FILL("confess"),\
    WORD_LIST_FILL("silk"),\
    WORD_LIST_FILL("jealous"),\
    WORD_LIST_FILL("lewd"),\
    WORD_LIST_FILL("undesirable"),\
    WORD_LIST_FILL("ambiguous"),\
    WORD_LIST_FILL("seed"),\
    WORD_LIST_FILL("carriage"),\
    WORD_LIST_FILL("screw"),\
    WORD_LIST_FILL("tick"),\
    WORD_LIST_FILL("eight"),\
    WORD_LIST_FILL("jellyfish"),\
    WORD_LIST_FILL("clip"),\
    WORD_LIST_FILL("frequent"),\
    WORD_LIST_FILL("wiggly"),\
    WORD_LIST_FILL("test"),\
    WORD_LIST_FILL("grade"),\
    WORD_LIST_FILL("hard"),\
    WORD_LIST_FILL("allow"),\
    WORD_LIST_FILL("curious"),\
    WORD_LIST_FILL("juggle"),\
    WORD_LIST_FILL("meat"),\
    WORD_LIST_FILL("nonchalant"),\
    WORD_LIST_FILL("cushion"),\
    WORD_LIST_FILL("shoes"),\
    WORD_LIST_FILL("pan"),\
    WORD_LIST_FILL("plausible"),\
    WORD_LIST_FILL("giants"),\
    WORD_LIST_FILL("best"),\
    WORD_LIST_FILL("watery"),\
    WORD_LIST_FILL("owe"),\
    WORD_LIST_FILL("shake"),\
    WORD_LIST_FILL("carpenter"),\
    WORD_LIST_FILL("messy"),\
    WORD_LIST_FILL("government"),\
    WORD_LIST_FILL("loud"),\
    WORD_LIST_FILL("long"),\
    WORD_LIST_FILL("natural"),\
    WORD_LIST_FILL("letters"),\
    WORD_LIST_FILL("foolish"),\
    WORD_LIST_FILL("callous"),\
    WORD_LIST_FILL("cobweb"),\
    WORD_LIST_FILL("prepare"),\
    WORD_LIST_FILL("concern"),\
    WORD_LIST_FILL("savory"),\
    WORD_LIST_FILL("van"),\
    WORD_LIST_FILL("magical"),\
    WORD_LIST_FILL("old"),\
    WORD_LIST_FILL("quick"),\
    WORD_LIST_FILL("death"),\
    WORD_LIST_FILL("staking"),\
    WORD_LIST_FILL("sweater"),\
    WORD_LIST_FILL("yam"),\
    WORD_LIST_FILL("proud"),\
    WORD_LIST_FILL("girls"),\
    WORD_LIST_FILL("parsimonious"),\
    WORD_LIST_FILL("marvelous"),\
    WORD_LIST_FILL("apparel"),\
    WORD_LIST_FILL("grouchy"),\
    WORD_LIST_FILL("depend"),\
    WORD_LIST_FILL("cakes"),\
    WORD_LIST_FILL("breathe"),\
    WORD_LIST_FILL("dock"),\
    WORD_LIST_FILL("rabid"),\
    WORD_LIST_FILL("book"),\
    WORD_LIST_FILL("ignore"),\
    WORD_LIST_FILL("whip"),\
    WORD_LIST_FILL("view"),\
    WORD_LIST_FILL("chunky"),\
    WORD_LIST_FILL("satisfy"),\
    WORD_LIST_FILL("foamy"),\
    WORD_LIST_FILL("mend"),\
    WORD_LIST_FILL("plain"),\
    WORD_LIST_FILL("tasty"),\
    WORD_LIST_FILL("young"),\
    WORD_LIST_FILL("closed"),\
    WORD_LIST_FILL("tickle"),\
    WORD_LIST_FILL("pointless"),\
    WORD_LIST_FILL("whirl"),\
    WORD_LIST_FILL("healthy"),\
    WORD_LIST_FILL("jewel"),\
    WORD_LIST_FILL("warn"),\
    WORD_LIST_FILL("pollution"),\
    WORD_LIST_FILL("responsible"),\
    WORD_LIST_FILL("agree"),\
    WORD_LIST_FILL("ashamed"),\
    WORD_LIST_FILL("rich"),\
    WORD_LIST_FILL("innocent"),\
    WORD_LIST_FILL("scatter"),\
    WORD_LIST_FILL("handle"),\
    WORD_LIST_FILL("obeisant"),\
    WORD_LIST_FILL("painful"),\
    WORD_LIST_FILL("rate"),\
    WORD_LIST_FILL("snakes"),\
    WORD_LIST_FILL("efficacious"),\
    WORD_LIST_FILL("doctor"),\
    WORD_LIST_FILL("misty"),\
    WORD_LIST_FILL("miss"),\
    WORD_LIST_FILL("white"),\
    WORD_LIST_FILL("exchange"),\
    WORD_LIST_FILL("lowly"),\
    WORD_LIST_FILL("tight"),\
    WORD_LIST_FILL("listen"),\
    WORD_LIST_FILL("hall"),\
    WORD_LIST_FILL("vein"),\
    WORD_LIST_FILL("hospital"),\
    WORD_LIST_FILL("kiss"),\
    WORD_LIST_FILL("same"),\
    WORD_LIST_FILL("promise"),\
    WORD_LIST_FILL("whispering"),\
    WORD_LIST_FILL("milky"),\
    WORD_LIST_FILL("dramatic"),\
    WORD_LIST_FILL("obey"),\
    WORD_LIST_FILL("ignorant"),\
    WORD_LIST_FILL("nauseating"),\
    WORD_LIST_FILL("absurd"),\
    WORD_LIST_FILL("request"),\
    WORD_LIST_FILL("value"),\
    WORD_LIST_FILL("observation"),\
    WORD_LIST_FILL("chivalrous"),\
    WORD_LIST_FILL("flower"),\
    WORD_LIST_FILL("exuberant"),\
    WORD_LIST_FILL("invite"),\
    WORD_LIST_FILL("farm"),\
    WORD_LIST_FILL("dust"),\
    WORD_LIST_FILL("refuse"),\
    WORD_LIST_FILL("wax"),\
    WORD_LIST_FILL("wrench"),\
    WORD_LIST_FILL("flash"),\
    WORD_LIST_FILL("tearful"),\
    WORD_LIST_FILL("pumped"),\
    WORD_LIST_FILL("bouncy"),\
    WORD_LIST_FILL("stick"),\
    WORD_LIST_FILL("bucket"),\
    WORD_LIST_FILL("stroke"),\
    WORD_LIST_FILL("unbecoming"),\
    WORD_LIST_FILL("wonderful"),\
    WORD_LIST_FILL("passenger"),\
    WORD_LIST_FILL("exotic"),\
    WORD_LIST_FILL("rob"),\
    WORD_LIST_FILL("nifty"),\
    WORD_LIST_FILL("detail"),\
    WORD_LIST_FILL("pathetic"),\
    WORD_LIST_FILL("insect"),\
    WORD_LIST_FILL("interesting"),\
    WORD_LIST_FILL("frame"),\
    WORD_LIST_FILL("erratic"),\
    WORD_LIST_FILL("quarrelsome"),\
    WORD_LIST_FILL("heap"),\
    WORD_LIST_FILL("bore"),\

#endif //__WORD_POOL_H__
