var annotated_dup =
[
    [ "Algorithms implemented in C (for education)", "index.html#autotoc_md32", null ],
    [ "Contribute Guidelines", "index.html#autotoc_md33", null ],
    [ "Overview about functions", "de/d20/md_data_structures_dictionary__r_e_a_d_m_e.html#autotoc_md9", null ],
    [ "Content", "d1/d12/md_data_structures_stack__r_e_a_d_m_e.html#autotoc_md11", null ],
    [ "Public interface", "d1/d12/md_data_structures_stack__r_e_a_d_m_e.html#autotoc_md12", null ],
    [ "Overview", "d7/db5/md_exercism__r_e_a_d_m_e.html#autotoc_md28", null ],
    [ "LeetCode Algorithm", "df/d58/md_leetcode__r_e_a_d_m_e.html#autotoc_md30", null ],
    [ "_big_int", "dc/d77/struct__big__int.html", "dc/d77/struct__big__int" ],
    [ "_large_num", "d3/d5a/struct__large__num.html", "d3/d5a/struct__large__num" ],
    [ "adaline", "d2/daa/structadaline.html", "d2/daa/structadaline" ],
    [ "array_3d", "d0/dc8/structarray__3d.html", "d0/dc8/structarray__3d" ],
    [ "AVLnode", "d2/d71/struct_a_v_lnode.html", "d2/d71/struct_a_v_lnode" ],
    [ "BSTIterator", "d4/d02/struct_b_s_t_iterator.html", "d4/d02/struct_b_s_t_iterator" ],
    [ "CArray", "d4/d2d/struct_c_array.html", "d4/d2d/struct_c_array" ],
    [ "contour", "d2/d89/structcontour.html", "d2/d89/structcontour" ],
    [ "data", "df/dea/structdata.html", "df/dea/structdata" ],
    [ "Dict", "d4/dfe/struct_dict.html", "d4/dfe/struct_dict" ],
    [ "dynamic_array", "d6/d42/structdynamic__array.html", "d6/d42/structdynamic__array" ],
    [ "Edge", "d5/db4/struct_edge.html", "d5/db4/struct_edge" ],
    [ "elem", "d0/d6b/structelem.html", "d0/d6b/structelem" ],
    [ "Graph", "d4/dd4/struct_graph.html", "d4/dd4/struct_graph" ],
    [ "GraphRep", "d2/d6a/struct_graph_rep.html", "d2/d6a/struct_graph_rep" ],
    [ "hash_set_t", "d0/df1/structhash__set__t.html", "d0/df1/structhash__set__t" ],
    [ "L", "df/db3/struct_l.html", "df/db3/struct_l" ],
    [ "max_heap", "d0/d8a/structmax__heap.html", "d0/d8a/structmax__heap" ],
    [ "min_heap", "de/dce/structmin__heap.html", "de/dce/structmin__heap" ],
    [ "Node", "db/d8b/struct_node.html", "db/d8b/struct_node" ],
    [ "node", "d5/da1/structnode.html", "d5/da1/structnode" ],
    [ "pid", "d0/d43/structpid.html", "d0/d43/structpid" ],
    [ "queue", "d2/d36/structqueue.html", "d2/d36/structqueue" ],
    [ "QueueRep", "d0/d10/struct_queue_rep.html", "d0/d10/struct_queue_rep" ],
    [ "Stack", "dd/d10/struct_stack.html", "dd/d10/struct_stack" ],
    [ "subset", "dc/de5/structsubset.html", "dc/de5/structsubset" ],
    [ "T", "d5/d7e/struct_t.html", "d5/d7e/struct_t" ],
    [ "tnode", "d8/d7a/structtnode.html", "d8/d7a/structtnode" ],
    [ "TrieNode", "da/d9b/struct_trie_node.html", "da/d9b/struct_trie_node" ],
    [ "word_count_word", "df/ddb/structword__count__word.html", "df/ddb/structword__count__word" ]
];